server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3305/temperatures?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 20031019qwe

#MQTT客户端
publish:
  mqtt:
    host: tcp://192.168.107.76:1883
    clientId: mqtt_publish
    options:
      userName: admin
      password: 20031019qwe
      # 这里表示会话不过期
      cleanSession: false
      # 配置一个默认的主题，加载时不会用到，只能在需要时手动提取
      defaultTopic: devops
      timeout: 1000
      KeepAliveInterval: 10
      #断线重连方式，自动重新连接与会话不过期配合使用会导致
      #断线重新连接后会接收到断线期间的消息。需要更改设置请看password联系我
      automaticReconnect: true
      connectionTimeout: 3000
      # 最大链接数
      maxInflight: 100
